apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: company-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AzzouzCherif/k8s-demo.git
    targetRevision: main
    path: app/root
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AzzouzCherif/k8s-demo.git
    targetRevision: main
    path: app/api
  destination:
    server: https://kubernetes.default.svc
    namespace: newappli-argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AzzouzCherif/k8s-demo.git
    targetRevision: main
    path: app/db
  destination:
    server: https://kubernetes.default.svc
    namespace: newappli-argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AzzouzCherif/k8s-demo.git
    targetRevision: main
    path: app/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: newappli-argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

